[versions]
accompanistSwiperefresh = "0.36.0"
androidGradlePlugin = "8.13.2"
glideVersion = "1.0.0-beta01"
datastorePreferences = "1.2.0"
kotlin = "2.2.21"
androidTools = "31.13.2"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
activityVersion = "1.12.2"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"
accompanist = "0.37.3"
androidDesugarJdkLibs = "2.1.5"
androidxAppCompat = "1.7.1"
androidxComposeAlpha = "1.10.0"
androidxComposeMaterial3Adaptive = "1.2.0"
androidxComposeMaterial3AdaptiveNavigationSuite = "1.4.0"
androidxCoreSplashscreen = "1.2.0"
androidxDataStore = "1.2.0"
androidxHiltNavigationCompose = "1.3.0"
androidxLifecycle = "2.10.0"
androidxNavigation = "2.9.6"
androidxWindowManager = "1.5.1"
androidxWork = "2.11.0"
coroutinesVersion = "1.10.2"
gmsPlugin = "4.4.4"
hilt = "2.57.2"
hiltExt = "1.3.0"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJson = "1.9.0"
ksp = "2.2.21-2.0.4"
media = "1.7.0"
media3Exoplayer = "1.9.0"
pagingRuntime = "3.3.6"
room = "2.8.4"
material = "1.13.0"
coil = "2.7.0"
androidxMetrics = "1.0.0"
timberVersion = "5.0.1"
gsonVersion = "2.13.2"
preferenceVersion = "1.2.1"
constraintlayoutCompose = "1.1.1"
paletteVersion = "1.0.0"
composeShapes = "1.1.0"
animationCompose = "1.10.0"
retrofitVersion = "3.0.0"
okhttp3Version = "5.3.2"
rxJava3Version = "3.1.12"
rxAndroid3Version = "3.0.2"
mapPlaceVersion = "17.1.0"
mapLocationVersion = "21.3.0"
material3Expressive = "1.0.0-alpha13"

[libraries]
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwiperefresh" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityVersion" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3Exoplayer" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3Exoplayer" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3Exoplayer" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingRuntime" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingRuntime" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preferenceVersion" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidxComposeAlpha" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-viewmodel-save-state = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }
androidx-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeTesting = { group = "androidx.lifecycle", name = "lifecycle-runtime-testing", version.ref = "androidxLifecycle" }

androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidxComposeAlpha" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "androidxComposeMaterial3Adaptive" }
androidx-compose-material3-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "androidxComposeMaterial3Adaptive" }
androidx-compose-material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "androidxComposeMaterial3Adaptive" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-window-core = { group = "androidx.window", name = "window-core", version.ref = "androidxWindowManager" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-palette-compose = { group = "androidx.palette", name = "palette-ktx", version.ref = "paletteVersion" }
compose-graphics-shapes = { group = "androidx.graphics", name = "graphics-shapes", version.ref = "composeShapes" }

play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "mapLocationVersion" }
play-services-places = { group = "com.google.android.gms", name = "play-services-places", version.ref = "mapPlaceVersion" }

androidx-animation-compose = { group = "androidx.compose.animation", name = "animation", version.ref = "animationCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-compose-material3-navigationSuite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "androidxComposeMaterial3AdaptiveNavigationSuite" }

androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-dataStore-core = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDataStore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }

androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "glideVersion" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }

room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-common = { group = "androidx.room", name = "room-common", version.ref = "room" }

kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesVersion" }
androidx-work-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timberVersion" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gsonVersion" }

retrofit = {group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion"}
retrofit-rxjava3-adapter = {group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofitVersion"}
retrofit-json-converter = {group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitVersion"}
okhttp = {group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3Version"}
okhttp-intercepter = {group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3Version"}

rx-java3 = {group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxJava3Version"}
rx-java3-android = {group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxAndroid3Version"}

coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }

lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "androidTools" }
lint-checks = { group = "com.android.tools.lint", name = "lint-checks", version.ref = "androidTools" }
lint-tests = { group = "com.android.tools.lint", name = "lint-tests", version.ref = "androidTools" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-metrics = { group = "androidx.metrics", name = "metrics-performance", version.ref = "androidxMetrics" }
javax-inject = { module = "javax.inject:javax.inject", version = "1" }
material3-expressive = { group = "androidx.xr.compose.material3", name = "material3", version.ref = "material3Expressive" }

[bundles]
androidx-core-dependencies = [
    "androidx-appcompat",
    "androidx-core-ktx",
    "androidx-preference",
    "androidx-activity-ktx",
    "androidx-activity-compose",
    "androidx-compose-foundation",
    "androidx-compose-foundation-layout",
    "androidx-compose-runtime",
]

androidx-material-dependencies = [
    "androidx-material3",
    "androidx-compose-material3-adaptive",
    "androidx-compose-material3-adaptive-layout",
    "androidx-compose-material3-adaptive-navigation",
    "androidx-compose-material3-windowSizeClass",
    "androidx-compose-material-iconsExtended",
    "androidx-window-core",
    "androidx-constraintlayout-compose",
    "androidx-palette-compose",
    "compose-graphics-shapes",
    "androidx-animation-compose",
    "material3-expressive"
]

androidx-lifecycle-dependencies = [
    "androidx-viewmodel-ktx",
    "androidx-lifecycle-viewModelCompose",
    "androidx-viewmodel-save-state",
    "androidx-livedata",
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-runtimeCompose",
    "androidx-lifecycle-service",
]

media3-dependencies = [
    "androidx-media3-exoplayer",
    "androidx-media3-ui",
    "androidx-media3-session"
]

room-dependencies = [
    "room-ktx",
    "room-runtime",
]

network-dependencies = [
    "retrofit",
    "retrofit-rxjava3-adapter",
    "retrofit-json-converter",
    "okhttp",
    "okhttp-intercepter",
    "gson",
]

rxjava3-dependencies = [
    "rx-java3",
    "rx-java3-android",
]

androidx-navigation-dependencies = [
    "androidx-navigation-compose",
    "androidx-compose-material3-navigationSuite",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
gms = { id = "com.google.gms.google-services", version.ref = "gmsPlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }

# Plugins defined by this project
quran-android-application = { id = "quran.android.application", version = "unspecified" }
quran-android-application-compose = { id = "quran.android.application.compose", version = "unspecified" }
quran-android-feature = { id = "quran.android.feature", version = "unspecified" }
quran-android-hilt = { id = "quran.android.hilt", version = "unspecified" }
quran-android-library = { id = "quran.android.library", version = "unspecified" }
quran-android-library-compose = { id = "quran.android.library.compose", version = "unspecified" }
quran-android-lint = { id = "quran.android.lint", version = "unspecified" }
quran-android-room = { id = "quran.android.room", version = "unspecified" }
quran-android-test = { id = "quran.android.test", version = "unspecified" }
quran-jvm-library = { id = "quran.jvm.library", version = "unspecified" }

